// UI Icons — lucide-react
export {
  Mail,
  MapPin,
  Phone,
  ExternalLink,
  ArrowRight,
  ArrowDown,
  Send,
  Code2,
  Layers,
  Terminal,
  Sun,
  Moon,
  Menu,
  X,
  CheckCircle2,
  AlertCircle,
  Loader2,
  Star,
  GitFork,
  Users,
  Briefcase,
  GraduationCap,
  Award,
  Zap,
  Package,
  ChevronRight,
  Search,
  User,
  Play,
  Square,
  Pause,
  BarChart2,
  Activity,
  Cpu,
  Wifi,
  Database,
  Cloud,
  GitBranch,
  ArrowUpRight,
  MonitorDot,
  FlaskConical,
  ZoomIn,
  ZoomOut,
  Maximize2,
  Clock,
  MessageSquare,
  Sparkles,
  Smile,
  Table2,
} from 'lucide-react'

// Social Icons — react-icons/fi (lucide doesn't include brand icons)
export { FiGithub as Github, FiLinkedin as Linkedin, FiTwitter as Twitter, FiInstagram as Instagram } from 'react-icons/fi'
export { FaSnapchatGhost as Snapchat } from 'react-icons/fa'
